name: build and deploy

on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"
      - name: Setup token
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
      - run: npm install -g yarn

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Yarn install with after reading cache
        run: yarn install

      - run: yarn build

      - run: npm publish
        if: github.ref == 'refs/heads/main'
      # - run: yarn deploy
